### ISSUE TITLE
Suggestion to add Ikos

### ISSUE THREAD

**Issue by vladp** [ksluckow/awesome-symbolic-execution#9]
Hello
may I suggest to add Ikos

https://github.com/NASA-SW-VnV/ikos

**Comment by ksluckow** [comment]
Yes, can you create a PR?

**Comment by vladp** [comment]
done
https://github.com/ksluckow/awesome-symbolic-execution/pull/13

**Comment by ksluckow** [comment]
Thanks for the PR!
